name:  setup version 

on:
  push:
    branches:
      - main

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:

      - name: show python version
        run: python --version

      - name: setup python version 3.10
        uses: actions/setup-python@v4
        with:
            python --version : '3.10'
      - name: show python version
        run : python --version
