name:  python-programs 

on:
  push:
    branches:
      - main

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name : install required requirements
        run : pip install pandas
      
      - name : install python program
        run : python text.py




      
