name: etl workflow

on:
  push:
    branches:
      - main

jobs:
    extract_data_workflow:
        runs-on: ubuntu_latest
        steps:
            - name: checkout code
            uses: checks/checkout@v2
            -name : print "extract_data"
            runs : python extract_data.py

    transform_data_workflow:
        runs-on: ubuntu_latest
        needs : extract_data_workflow
        steps:
            -name: checkout code
            uses: checks/checkout@v2
            -name : print "transform_data"
            runs : python transform_data.py

    load_data_workflow:
        runs-on: ubuntu_latest
        needs : transform_data_workflow
        steps:
            -name: checkout code
            uses: checks/checkout@v2
            -name : print "load_data"
            runs : python load_data.py


  
    

  